# file: config_framework.py

import argparse
import math
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

TICK_HZ = 100000

@dataclass
class Task:
    name: str
    period: float
    priority: int
    deadline: float = None
    stack: int = 256
    phase: float = 0
    wcet: float = None

    def __post_init__(self):
        if self.deadline is None:
            self.deadline = self.period


def load(path):
    raw = yaml.safe_load(Path(path).read_text())
    sched = raw.get("scheduler", {}) or {}
    tasks = [
        Task(
            name=t["name"], period=t["period_ms"], priority=t["priority"],
            deadline=t.get("deadline_ms"), stack=t.get("stack_words", 256),
            phase=t.get("phase_ms", 0), wcet=t.get("wcet_ms"),
        )
        for t in raw["tasks"]
    ]
    policy = sched.get("policy", "SKIP")
    return tasks, {
        "policy": policy,
        "max_tasks": sched.get("max_tasks", 8),
        "trace": sched.get("trace_enabled", True),
    }


def to_ticks(tasks, tick_hz):
    for t in tasks:
        t.period = math.floor(t.period * tick_hz / 1000)
        t.deadline = math.floor(t.deadline * tick_hz / 1000)
        if t.wcet is not None:
            t.wcet = math.ceil(t.wcet * tick_hz / 1000)


def response_time(task, higher):
    w = task.wcet
    while True:
        w_next = task.wcet + sum(math.ceil(w / h.period) * h.wcet for h in higher)
        if w_next == w or w_next > task.deadline:
            return w_next
        
        w = w_next


def analyze(tasks, tick_hz):
    to_ticks(tasks, tick_hz)

    print(f"tick_hz = {tick_hz}  (1 tick = {1000 / tick_hz:.3f} ms)")
    print(f"{'task':<16}{'T(tick)':>8}{'D(tick)':>8}{'C(tick)':>8}{'R(tick)':>8}  result")

    ok = True
    for t in tasks:
        higher = [h for h in tasks if h.priority > t.priority]
        r = response_time(t, higher)
        passed = r <= t.deadline
        ok &= passed
        print(f"{t.name:<16}{t.period:>8}{t.deadline:>8}{t.wcet:>8}{r:>8}  {'OK' if passed else 'MISS'}")

    print("SCHEDULABLE" if ok else "NOT SCHEDULABLE")
    return ok


MAIN_C = '''/* Auto-generated by config_framework.py */

#include "FreeRTOS.h"
#include "task.h"
#include "ptl.h"
#include "uart.h"
#include "tasks.h"

int main( void )
{{
    UART_init();

    SchedulerConfig_t xSchedCfg = {{
        .maxTasks = {max_tasks},
        .xPolicy = PTL_OVERRUN_{policy},
        .xTraceEnabled = {trace}
    }};

    if ( xPTL_Init( &xSchedCfg ) != PTL_OK )
    {{
        UART_printf( "[FATAL] PTL_Init failed\\n" );
        for ( ;; );
    }}

{configs}
{creates}
    xPTL_Start();
    for ( ;; );
}}
'''

CFG = '''    PTL_TaskConfig_t x{n}Cfg = {{
        .pcTaskName = "{n}",
        .PTL_JobFunction_t = v{n}Task,
        .usStack_size = {stack},
        .xPriority = {priority},
        .xPeriod = pdMS_TO_TICKS( {period:.0f} ),
        .xDeadline = pdMS_TO_TICKS( {deadline:.0f} ),
        .pArg = NULL,
        .xPhase = pdMS_TO_TICKS( {phase:.0f} )
    }};
'''

STUB = '''void v{n}Task( void *pArg )
{{
    ( void ) pArg;
}}
'''

FREERTOS_CONFIG_H = '''/*
 * PTL V1.0.0
 * Copyright (C) 2026 Group3.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * https://www.FreeRTOS.org
 * https://github.com/FreeRTOS
 *
 */


#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

#define configUSE_TASK_NOTIFICATIONS     1

#define INCLUDE_xTaskGetCurrentTaskHandle 1

#define configUSE_TICK_HOOK              1
#define configUSE_IDLE_HOOK              1

#define configSUPPORT_STATIC_ALLOCATION  0
#define configSUPPORT_DYNAMIC_ALLOCATION 1
#define configUSE_MALLOC_FAILED_HOOK     1

#define INCLUDE_vTaskDelete              1
#define INCLUDE_vTaskSuspend             1

#define configUSE_TICKLESS_IDLE          0

#define SVC_Handler     vPortSVCHandler
#define PendSV_Handler  xPortPendSVHandler
#define SysTick_Handler xPortSysTickHandler

#define tskIDLE_PRIORITY                ( ( UBaseType_t ) 0U )
#define configUSE_PREEMPTION            1
#define configUSE_TIME_SLICING          1

#define configCPU_CLOCK_HZ              ( ( unsigned long ) 50000000 )
#define configTICK_RATE_HZ              ( ( TickType_t ) {tick_hz} )

#define configMAX_PRIORITIES            5
#define configMINIMAL_STACK_SIZE        128
#define configTOTAL_HEAP_SIZE           ( 64 * 1024 )
#define configMAX_TASK_NAME_LEN         20
#define configUSE_16_BIT_TICKS          0

#define configUSE_MUTEXES               1
#define configUSE_COUNTING_SEMAPHORES   1

#define configUSE_TRACE_FACILITY        1
#define INCLUDE_eTaskGetState            1

#define configUSE_TIMERS                1
#define configTIMER_TASK_PRIORITY       configMAX_PRIORITIES - 1
#define configTIMER_QUEUE_LENGTH        10
#define configTIMER_TASK_STACK_DEPTH    ( configMINIMAL_STACK_SIZE * 3 )

#define configCHECK_FOR_STACK_OVERFLOW  2
#define configKERNEL_INTERRUPT_PRIORITY         255
#define configMAX_SYSCALL_INTERRUPT_PRIORITY    191

#endif
'''


def generate(tasks, cfg, out_dir):
    out = Path(out_dir)
    (out / "src").mkdir(parents=True, exist_ok=True)
    (out / "include").mkdir(parents=True, exist_ok=True)

    configs = "\n".join(CFG.format(n=t.name, stack=t.stack, priority=t.priority, period=t.period, deadline=t.deadline, phase=t.phase) for t in tasks)
    creates = "\n".join(f"    xPTL_CreateTask( &x{t.name}Cfg, NULL );" for t in tasks)

    (out / "src" / "main.c").write_text(MAIN_C.format(
        max_tasks=cfg["max_tasks"], policy=cfg["policy"],
        trace="pdTRUE" if cfg["trace"] else "pdFALSE", configs=configs, creates=creates))

    protos = "\n".join(f"void v{t.name}Task( void *pArg );" for t in tasks)
    (out / "include" / "tasks.h").write_text(
        f'#ifndef TASKS_H\n#define TASKS_H\n\n#include "FreeRTOS.h"\n#include "task.h"\n\n{protos}\n#endif\n')

    tasks_c = out / "src" / "tasks.c"
    if not tasks_c.exists():
        stubs = "\n".join(STUB.format(n=t.name) for t in tasks)
        tasks_c.write_text(f'#include "tasks.h"\n#include "ptl.h"\n\n{stubs}')

    (out / "include" / "FreeRTOSConfig.h").write_text(
        FREERTOS_CONFIG_H.format(tick_hz=TICK_HZ))

    print(f"generated in {out}/")


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("analyze")
    a.add_argument("file")

    g = sub.add_parser("generate")
    g.add_argument("file")
    g.add_argument("-o", "--output", default="generated")

    args = p.parse_args()
    tasks, cfg = load(args.file)

    if args.cmd == "analyze":
        sys.exit(0 if analyze(tasks, TICK_HZ) else 1)
    else:
        generate(tasks, cfg, args.output)


if __name__ == "__main__":
    main()